<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FaceRecognize.Abstractions\FaceRecognize.Abstractions.csproj" />
    <ProjectReference Include="..\FaceRecognize.Core\FaceRecognize.Core.csproj" />
    <ProjectReference Include="..\FaceRecognize.Data\FaceRecognize.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.*" />
    <PackageReference Include="OpenCvSharp5.WpfExtensions" Version="5.0.0.20260702" />
  </ItemGroup>

</Project>
